package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/robbert229/swagger-download-file-bug/models"
)

// HTTP code for type GetFileOK
const GetFileOKCode int = 200

/*GetFileOK download a file

swagger:response getFileOK
*/
type GetFileOK struct {

	/*
	  In: Body
	*/
	Payload runtime.File `json:"body,omitempty"`
}

// NewGetFileOK creates GetFileOK with default headers values
func NewGetFileOK() *GetFileOK {
	return &GetFileOK{}
}

// WithPayload adds the payload to the get file o k response
func (o *GetFileOK) WithPayload(payload runtime.File) *GetFileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get file o k response
func (o *GetFileOK) SetPayload(payload runtime.File) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetFileDefault Unexpected error

swagger:response getFileDefault
*/
type GetFileDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetFileDefault creates GetFileDefault with default headers values
func NewGetFileDefault(code int) *GetFileDefault {
	if code <= 0 {
		code = 500
	}

	return &GetFileDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get file default response
func (o *GetFileDefault) WithStatusCode(code int) *GetFileDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get file default response
func (o *GetFileDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get file default response
func (o *GetFileDefault) WithPayload(payload *models.Error) *GetFileDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get file default response
func (o *GetFileDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFileDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
