package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewPostFileParams creates a new PostFileParams object
// with the default values initialized.
func NewPostFileParams() PostFileParams {
	var ()
	return PostFileParams{}
}

// PostFileParams contains all the bound params for the post file operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostFile
type PostFileParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: formData
	*/
	Attachment runtime.File
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PostFileParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return err
		} else if err := r.ParseForm(); err != nil {
			return err
		}
	}

	attachment, attachmentHeader, err := r.FormFile("attachment")
	if err != nil {
		res = append(res, errors.New(400, "reading file %q failed: %v", "attachment", err))
	} else {
		o.Attachment = runtime.File{Data: attachment, Header: attachmentHeader}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
